// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dab2_EfCore.Data;

#nullable disable

namespace dab2_EfCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("dab2_EfCore.Models.Chairman", b =>
                {
                    b.Property<int>("Member_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Member_id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cpr_number")
                        .HasColumnType("int");

                    b.Property<int>("Cvr_number")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Member_id");

                    b.HasIndex("Cvr_number")
                        .IsUnique();

                    b.ToTable("Chairmen");
                });

            modelBuilder.Entity("dab2_EfCore.Models.Location", b =>
                {
                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Bathroom")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosingTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MunicipalityZipcode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OpeningTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Zipcode")
                        .HasColumnType("int");

                    b.HasKey("Address");

                    b.HasIndex("MunicipalityZipcode");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("dab2_EfCore.Models.Member", b =>
                {
                    b.Property<int>("Member_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Member_id"), 1L, 1);

                    b.Property<int>("Cvr_number")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SocietyCvr_number")
                        .HasColumnType("int");

                    b.HasKey("Member_id");

                    b.HasIndex("SocietyCvr_number");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("dab2_EfCore.Models.Municipality", b =>
                {
                    b.Property<int>("Zipcode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Zipcode"), 1L, 1);

                    b.Property<int>("AccessKey")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Zipcode");

                    b.ToTable("Municipalities");
                });

            modelBuilder.Entity("dab2_EfCore.Models.Room", b =>
                {
                    b.Property<int?>("RoomNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("RoomNumber"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("LocationAddress")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoomNumber");

                    b.HasIndex("LocationAddress");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("dab2_EfCore.Models.Society", b =>
                {
                    b.Property<int>("Cvr_number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cvr_number"), 1L, 1);

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MunicipalityZipcode")
                        .HasColumnType("int");

                    b.Property<int>("Zip_code")
                        .HasColumnType("int");

                    b.HasKey("Cvr_number");

                    b.HasIndex("MunicipalityZipcode");

                    b.ToTable("Societies");
                });

            modelBuilder.Entity("dab2_EfCore.Models.Chairman", b =>
                {
                    b.HasOne("dab2_EfCore.Models.Society", "Society")
                        .WithOne("Chairman")
                        .HasForeignKey("dab2_EfCore.Models.Chairman", "Cvr_number")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Society");
                });

            modelBuilder.Entity("dab2_EfCore.Models.Location", b =>
                {
                    b.HasOne("dab2_EfCore.Models.Municipality", "Municipality")
                        .WithMany("Locations")
                        .HasForeignKey("MunicipalityZipcode");

                    b.Navigation("Municipality");
                });

            modelBuilder.Entity("dab2_EfCore.Models.Member", b =>
                {
                    b.HasOne("dab2_EfCore.Models.Society", "Society")
                        .WithMany("Members")
                        .HasForeignKey("SocietyCvr_number")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Society");
                });

            modelBuilder.Entity("dab2_EfCore.Models.Room", b =>
                {
                    b.HasOne("dab2_EfCore.Models.Location", "Location")
                        .WithMany("Rooms")
                        .HasForeignKey("LocationAddress");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("dab2_EfCore.Models.Society", b =>
                {
                    b.HasOne("dab2_EfCore.Models.Municipality", null)
                        .WithMany("ListOfSocieties")
                        .HasForeignKey("MunicipalityZipcode");
                });

            modelBuilder.Entity("dab2_EfCore.Models.Location", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("dab2_EfCore.Models.Municipality", b =>
                {
                    b.Navigation("ListOfSocieties");

                    b.Navigation("Locations");
                });

            modelBuilder.Entity("dab2_EfCore.Models.Society", b =>
                {
                    b.Navigation("Chairman")
                        .IsRequired();

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
